### ISSUE TITLE
Can App.config's be used within NSpec test projects?

### ISSUE THREAD

**Issue by goneale** [osoftware/NSpecTestAdapter#4]
I can't seem to resolve any AppSettings or sections via ConfigurationManager. I don't think App.config is being incorporated correctly?

I tried manually placing it into the current running test folder, but no luck.

**Comment by goneale** [comment]
I have adjusted the test adapter to support this @osoftware, I am not yet familiar with submitting GitHub pull requests, but could take a shot if you would like to take on this enhancement.

**Comment by osoftware** [comment]
You're welcome. Just click fork, commit your changes and create a pull request in pull requests section. Not that hard.

**Comment by osoftware** [comment]
Released in 0.3.0.
